### ISSUE TITLE
Login Admin

### ISSUE THREAD

**Issue by ycadet971** [jRimbault/pa-cli#24]

**Comment by jRimbault** [comment]
Déjà fait depuis [longtemps][0], c'est côté serveur qu'il faut corriger l'authentification.

[0]: https://github.com/jRimbault/pa-cli/blame/master/src/main/java/esgi/core/RestConnector.java#L57

**Comment by ycadet971** [comment]
Oui mais sur la vue

**Comment by jRimbault** [comment]
Toutes les requêtes à l'api passent par la.
